import pytest
from types import SimpleNamespace

from mlonmcu.environment.config import PythonConfig
from mlonmcu.setup.gen_requirements import get_extra_requirements, merge_requirements
from mlonmcu.setup.setup import Setup


def test_merge_requirements_deduplicates_and_combines_constraints():
    requirements = merge_requirements(["tflite", "tflite==2.18.0", "PyYAML", "pyyaml==6.0.*"])

    assert requirements == ["tflite==2.18.0", "PyYAML==6.0.*"]


def test_merge_requirements_rejects_conflicting_pins():
    with pytest.raises(ValueError, match="Conflicting version requirements for construct"):
        merge_requirements(["construct==2.10.54", "construct==2.10.68"])


def test_get_extra_requirements_reads_pyproject_extra_file():
    requirements = get_extra_requirements(["cfu"])

    assert "construct==2.10.68" in requirements


def test_get_extra_requirements_rejects_single_extra_string():
    with pytest.raises(ValueError, match="python.extra must be a list of strings"):
        get_extra_requirements("cfu")


def test_setup_generation_merges_workspace_and_selected_requirements(tmp_path, monkeypatch):
    environment = SimpleNamespace(
        home=tmp_path,
        python=PythonConfig(requirements=["tflite==2.18.0"]),
        frameworks=[],
        frontends=[],
        platforms=[SimpleNamespace(name="tflite", enabled=True)],
        targets=[],
        vars={},
    )
    context = SimpleNamespace(environment=environment, cache={})
    monkeypatch.setattr(
        "mlonmcu.setup.gen_requirements.join_requirements",
        lambda: {"tflite": ("Requirements for using tflite", ["tensorflow", "tflite"])},
    )

    Setup(context=context).generate_requirements()

    assert (tmp_path / "requirements_addition.txt").read_text().splitlines() == [
        "# AUTOGENERATED by 'mlonmcu setup -g' ",
        "tensorflow",
        "tflite==2.18.0",
    ]
